"""make scan_job_id nullable

Revision ID: 84633cd16702
Revises: 35a9e1d5d4c1
Create Date: 2026-02-28 23:24:42.001556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84633cd16702'
down_revision: Union[str, None] = '35a9e1d5d4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_exam_set_version', 'answer_keys', ['exam_id', 'set_id', 'version'])
    op.create_foreign_key(None, 'answer_keys', 'exam_sets', ['set_id'], ['id'])
    op.alter_column('exams', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('exams', 'subject_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index('idx_exams_user_created', 'exams', ['teacher_id', 'date_created'], unique=False)
    op.alter_column('scanned_sheets', 'scan_job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scanned_sheets', 'scan_job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_exams_user_created', table_name='exams')
    op.alter_column('exams', 'subject_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('exams', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'answer_keys', type_='foreignkey')
    op.drop_constraint('uq_exam_set_version', 'answer_keys', type_='unique')
    # ### end Alembic commands ###
