"""Add template_type

Revision ID: f240f973f48f
Revises: 84633cd16702
Create Date: 2026-03-07 20:06:44.719314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f240f973f48f'
down_revision: Union[str, None] = '84633cd16702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('template_type', sa.String(length=50), nullable=False, server_default='auto'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'template_type')
    # ### end Alembic commands ###
